#ifndef __DEEP_ENGINE_DRAWABLE_TYPES_H__
#define __DEEP_ENGINE_DRAWABLE_TYPES_H__

#define DE_DRAWABLE_TYPE_PIXEL     0
#define DE_DRAWABLE_TYPE_TRIANGLE  1
#define DE_DRAWABLE_TYPE_LINE      2
#define DE_DRAWABLE_TYPE_RECTANGLE 3

#endif